apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-api
  description: Example repo node basic
  tags:
    - node
    - microservices
  links:
    - url: https://github.com/roxsross/web-nodejs-basic
      title: Source Code
      icon: github
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.      
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: node-basic
